name: Build LaTeX Document and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:  # allows you to run the workflow manually from the Actions tab

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: Thesis
          root_file: tjumain.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Create Public Dir
        run: mkdir -p public
      - name: Copy PDF to Public Dir
        run: cp Thesis/tjumain.pdf Thesis/index.html public/
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
